### ISSUE TITLE
[Question] Custom items compatibility?

### ISSUE THREAD

**Issue by Futodama** [ds58/Panilla#125]
Is there a chance that I will buy your plugin and it will make it unrealistic to use my custom items?
For example, there are a huge number of "ItemAdder" items and other plugins.
Will they be affected by installing this plugin?

If there is this possibility, can you make it compatible with plugins from my list so that I can safely put your plugin on my server?

**Comment by ds58** [comment]
Hi,

I believe there are other users of Panilla who use the ItemAdder plugin. You are able to whitelist NBT tags so that Panilla doesn't interfere at all. You should run a test to make sure it works the way you expect. If it doesn't, I can help you whitelist the NBT tags you need.

If it doesn't work for you, you can send me a DM on the SpigotMC forums and I'd be happy to refund you.
